[versions]
agp = "8.8.2"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.10.0"
constraintlayout = "2.2.0"
design = "28.0.0"
playServicesLocation = "21.3.0"
multidex = "1.0.3"
playServicesMapsLicense = "12.0.1"
playServicesLocationLicense = "12.0.1"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
design = { group = "com.android.support", name = "design", version.ref = "design" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "playServicesLocation" }
multidex = { group = "com.android.support", name = "multidex", version.ref = "multidex" }
play-services-maps-license = { group = "com.google.android.gms", name = "play-services-maps-license", version.ref = "playServicesMapsLicense" }
play-services-location-license = { group = "com.google.android.gms", name = "play-services-location-license", version.ref = "playServicesLocationLicense" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

